version: "3"

services:
  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile.dynamodb
    command: -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data -sharedDb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  dynamodb-admin:
    build:
      context: .
      dockerfile: Dockerfile.dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - "8001:8001"

volumes:
  dynamodb_data:
